<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container6HkW3Gp\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container6HkW3Gp/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container6HkW3Gp.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container6HkW3Gp\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container6HkW3Gp\App_KernelDevDebugContainer([
    'container.build_hash' => '6HkW3Gp',
    'container.build_id' => '35cc4675',
    'container.build_time' => 1643778948,
], __DIR__.\DIRECTORY_SEPARATOR.'Container6HkW3Gp');
